name: Update Python Repos Chart

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  update-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests pygal

      - name: Run script to generate chart
        run: |
          python scripts/python_repos.py

      - name: Commit and push updated chart
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add python_repos.svg
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update chart $(date +'%Y-%m-%d')"
            git push
          else
            echo "No changes to commit"
          fi
